### ISSUE TITLE
Add more chains like Scroll and Arbitrum

### ISSUE THREAD

**Issue by felix9607** [Cryptorubic/rubic-widget#9]
Hi,

is it possible to add chains like Scroll or Arbitrum, like on your official website? I see you are not using the widget itself there but I don't see why there is such a huge capability gap between the widget and the sdk.

Any future plans to include more chains maybe?

Thanks

**Comment by axtezy** [comment]
Hi, We are going to freeze the old version of the widget (with the old design) and release a new version in a few weeks, similar to our current app design, which will contain the latest SDK features.
